name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo CLI
        run: npm install -g @expo/cli

      - name: Build for web
        env:
          EXPO_PUBLIC_SUPABASE_URL: ${{ secrets.EXPO_PUBLIC_SUPABASE_URL }}
          EXPO_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.EXPO_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build:web

      - name: Copy 404.html for SPA routing
        run: cp public/404.html dist/404.html

      - name: Fix paths for GitHub Pages subpath
        run: |
          # HTML 파일들에서 절대 경로를 상대 경로로 변경
          find dist -name "*.html" -type f -exec sed -i 's|src="/_expo|src="/easy-to-do/_expo|g' {} \;
          find dist -name "*.html" -type f -exec sed -i 's|href="/favicon.ico"|href="/easy-to-do/favicon.ico"|g' {} \;
          find dist -name "*.html" -type f -exec sed -i 's|href="/"|href="/easy-to-do/"|g' {} \;

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
